# Generated by Django 3.1.7 on 2021-03-31 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0005_auto_20210329_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('salary', models.FloatField(max_length=20)),
                ('image', models.FileField(null=True, upload_to='')),
                ('description', models.TextField(max_length=500, null=True)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('Location', models.CharField(max_length=50, null=True)),
                ('skills', models.TextField(max_length=500, null=True)),
                ('creationdate', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appp.recruiter')),
            ],
        ),
    ]
